# Generated by Django 4.1.4 on 2024-01-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_slug', models.SlugField(blank=True, null=True)),
                ('product_price', models.FloatField()),
                ('product_stock', models.IntegerField(default=True)),
                ('product_discountprice', models.FloatField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_cover_image', models.ImageField(upload_to='static/cover/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.category')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.ImageField(upload_to='stactic/photos/')),
                ('photo_slug', models.SlugField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.product')),
            ],
        ),
    ]
