# Generated by Django 4.1.4 on 2024-01-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active_active_on_home_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
