# Generated by Django 4.1.4 on 2024-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_active_active_on_home_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cleaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
