# Generated by Django 4.1.4 on 2024-04-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_photo_is_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='product_image',
            field=models.ImageField(upload_to='static/photos/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='variationimages',
            name='variation_image',
            field=models.ImageField(upload_to='static/variation_images/', verbose_name='variation_image'),
        ),
    ]
