# Generated by Django 4.1.4 on 2024-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/header'),
        ),
    ]
