# Generated by Django 4.1.4 on 2024-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='derivery_method',
            field=models.CharField(choices=[('DHL', 'DHL'), ('Colissimo', 'Colissimo')], default='Colissimo', max_length=10),
        ),
    ]
