# Generated by Django 4.1.4 on 2024-03-21 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_derivery_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='derivery_method',
            new_name='delivery_method',
        ),
    ]
