# Generated by Django 4.1.4 on 2024-03-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('DHL', 'DHL'), ('Colissimo', 'Colissimo')], max_length=10),
        ),
    ]
